[slack.myslack]
PrefixMessagesWithNick=true

[discord.mydiscord]
Server="698613972928299079"

[general]
RemoteNickFormat="[{PROTOCOL}/{BRIDGE}] <{NICK}> "

[[gateway]]
    name = "mygateway"
    enable=true

    [[gateway.inout]]
    account = "discord.mydiscord"
    channel="general"

    [[gateway.inout]]
    account ="slack.myslack"
    channel = "discord"
