[slack]
[slack.myslack]
PrefixMessagesWithNick=true

[discord]
[discord.mydiscord]
Server="yourdiscordservername"

[general]
RemoteNickFormat="[{PROTOCOL}/{BRIDGE}] <{NICK}> "

[[gateway]]
    name = "mygateway"
    enable=true

    [[gateway.inout]]
    account = "discord.mydiscord"
    channel="general"

    [[gateway.inout]]
    account ="slack.myslack"
    channel = "discord-bots"
