[slack.myslack]
PrefixMessagesWithNick=true
RemoteNickFormat="@{NICK}"

[discord.mydiscord]
Server="698613972928299079"
ShowEmbeds=true

[gitter.mygitter]
RemoteNickFormat="<{NICK}> "
#This improves the situation where a gitter user uploads a picture/file, just relay the link instead of the Markdown
ReplaceMessages=[["^\\[!\\[[^\\]]+\\]\\(https?:\\/\\/files\\.gitter\\.im\\/[^\\/]+\\/[^\\/]+\\/[^\\/]+\\/thumb\\/[^\\)]+\\)\\]\\(([^\\)]+)\\)$", "$1"], ["\\[[^\\]]+\\]\\((https:\\/\\/files\\.gitter\\.im\\/[^\\/]+\\/[^\\/]+\\/[^\\/]+\\/[^\\)]+)\\)$", "$1"]]

[general]
RemoteNickFormat=""

[[gateway]]
    name = "mygateway"
    enable=true

    [[gateway.inout]]
    account = "gitter.mygitter"
    channel="wpivex/ot-slacktesting"

    [[gateway.inout]]
    account ="slack.myslack"
    channel = "ot-slacktesting"
