[slack.myslack]
PrefixMessagesWithNick=false

[discord.mydiscord]
Server="698613972928299079"
ShowEmbeds=true

[general]
RemoteNickFormat=""

[[gateway]]
    name = "mygateway"
    enable=true

    [[gateway.inout]]
    account = "discord.mydiscord"
    channel="general"

    [[gateway.inout]]
    account ="slack.myslack"
    channel = "discord"
